% Import raw data; compute channel magnitudes from components
cl_importmul('/Volumes/t3/127/rs/full/source-frontal/clean-mul',...
	     '/Volumes/t3/127/rs/full/original/raw-set',...
	     'data/rs/full/source-frontal/set', 'frontal');
cl_importmul('/Volumes/t3/118/rs/full/source-frontal/clean-mul',...
	     '/Volumes/t3/118/rs/full/original/raw-set',...
	     'data/rs/full/source-frontal/set', 'frontal');

% Add event-related information to identify clean segments in data
cl_modifyeventsEMSE('data/rs/full/source-frontal/set', 'data/rs/full/evt',...
		'data/rs/full/source-frontal/MagEvtFiltCAR-set', {'C', 'O'});

% Apply 0.5 - 45 Hz bandpass filter
cl_bandpassfilter('data/rs/full/source-frontal/MagEvtFiltCAR-set',...
		  'data/rs/full/source-frontal/MagEvtFiltCAR-set', 0.5, 45);

% Re-reference data to common average
cl_rereference('data/rs/full/source-frontal/MagEvtFiltCAR-set',...
	       'data/rs/full/source-frontal/MagEvtFiltCAR-set', 'CAR');

% Convert files to .mat format for importing into Python
% mkdir data/rs/full/source-frontal/mat-MagEvtFiltCAR
set_mat_converter('data/rs/full/source-frontal/MagEvtFiltCAR-set',...
	          'data/rs/full/source-frontal/MagEvtFiltCAR-mat');
